# Cloud Build configuration for SolarMatch frontend
# This allows passing secrets as build arguments

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_GOOGLE_MAPS_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_BACKEND_URL=${_BACKEND_URL}'
      - '-t'
      - '$_IMAGE_NAME'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_IMAGE_NAME'

images:
  - '$_IMAGE_NAME'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions with default values
substitutions:
  _GOOGLE_MAPS_API_KEY: ''
  _BACKEND_URL: ''
  _IMAGE_NAME: ''
